sistema/urls.py
from django.urls import path

from . import views

app_name = 'sistema'
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:assunto_id>/", views.questionario, name="questionario"),
]

testes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sistema/', include("sistema.urls")),
    path('admin/', admin.site.urls),
]

sistema/models.py
from django.db import models

class Assunto(models.Model):
    assunto = models.CharField(max_length=100)

    def __str__(self):
        return self.assunto

class Questao(models.Model):
    enunciado = models.CharField(max_length=300)
    assunto = models.ForeignKey(Assunto, related_name='questoes', on_delete=models.SET_NULL, null=True)
    solucao = models.TextField(max_length=1000)

    def __str__(self):
        return self.enunciado

class Alternativa(models.Model):
    questao = models.ForeignKey(Questao, related_name='alternativas', on_delete=models.CASCADE)
    alternativa = models.CharField(max_length=200)

    def __str__(self):
        return self.alternativa

class MultiplaEscolha(Questao):

    def __str__(self):
        return self.enunciado

class VerdadeiroOuFalso(Questao):
    pass

sistema/views.py
from django.http import Http404
from django.shortcuts import render

from .models import Assunto


def questionario(request, assunto_id):
    try:
        assunto = Assunto.objects.get(id=assunto_id)
    except Assunto.DoesNotExist:
        raise Http404("Assunto invalido")

    lista_questoes = assunto.questoes.all()

    context = {
        "assunto": assunto,
        "lista_questoes": lista_questoes
    }

    return render(request, "questionario.html", context)

def index(request):
    assuntos = Assunto.objects.all().order_by()
    context = {"assuntos": assuntos}
    return render(request, "index.html", context)

sistema/templates/index.html
<style>
    body {
        background-color: rgb(221, 212, 163);
    }

    main {
        max-width: 900px;
        padding: 20px;
        margin: auto;
        border-radius: 10px;
        background-color: white;
    }

    h1 {
        text-align: center;
    }

    button {
        display: block;
        margin: auto;
    }

    .titulo-solucao {
        background-color: #f1f1f1;
        border: 1px solid #ccc;
        padding: 10px;
        cursor: pointer;
        width: fit-content;
        border-radius: 5px;
        font-weight: bold;
    }

    /* Estilizando o conteúdo que será mostrado/oculto */
    .solucao {
        margin-top: 10px;
    }
    
</style>


<body>
<main>
<h1>Sistema de Monitoramento</h1>
<hr>
{% if assuntos %}
    <h2>Assuntos:</h2>
    <ul>
    {% for assunto in assuntos %}
        <li><a href="{% url 'sistema:questionario' assunto.id %}">{{ assunto.assunto }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nenhum assunto até o momento.</p>
{% endif %}
</main>
</body>

sistema/templates/questionario.html
<!-- MathJax -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

<script type="text/javascript">
    MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
        displayMath: [['$$', '$$'], ['\\[', '\\]']],
        macros: {
          degree: "{^{\\circ}}",  // Define \degree as the ° symbol
          sen: "\\operatorname{sen}",  // Define \sen to display as "sen"
          tg: "\\operatorname{tg}" 
        }
      }
    };
    
    document.querySelector('.titulo-solucao').addEventListener('click', function () {
        var solucao = document.querySelector('.solucao');
        if (solucao.style.display === 'none') {
            solucao.style.display = 'block';
        } else {
            solucao.style.display = 'none';
        }
    });
</script>

<style>
    body {
        background-color: rgb(221, 212, 163);
    }

    main {
        max-width: 900px;
        padding: 20px;
        margin: auto;
        border-radius: 10px;
        background-color: white;
    }

    h1 {
        text-align: center;
    }

    button {
        display: block;
        margin: auto;
    }

    .titulo-solucao {
        background-color: #f1f1f1;
        border: 1px solid #ccc;
        padding: 10px;
        cursor: pointer;
        width: fit-content;
        border-radius: 5px;
        font-weight: bold;
    }

    /* Estilizando o conteúdo que será mostrado/oculto */
    .solucao {
        margin-top: 10px;
    }
    
</style>


<body>
<main>

<h1>Questionario sobre {{ assunto.assunto }}</h1>

<hr>

{% if lista_questoes %}

<ol class="lista-questoes">

    {% for questao in lista_questoes %}

    <li class="questao">
        <p class="enunciado">
            {{ questao.enunciado }}
        </p>

        <ul class="alternativas">
            {% for alternativa in questao.alternativas.all %}
            <li>
                <input type="radio" name="alternativa" id="opcao1">
                <label for="opcao1">{{ alternativa.alternativa }}</label>
            </li>
            {% endfor %}
        </ul>

        <section class="solucao">
            <p class="titulo-solucao">Solução</p>

            <p class="solucao">
                {{ questao.solucao }}
            </p>
        </section>
    </li>

    {% endfor %}

</ol>

<button>Enviar</button>
{% else %}
    <p>Assunto sem questoes no momento.</p>
{% endif %}
</main>
</body>